### PR TITLE
Search bar workflow

### PR DESCRIPTION
**Pull request by steve111MV**
- responding to search entry on App main SearchBar
- Css adjusted to allow schrolling inside App main Content
- The search result appears on App main Content

### CODE REVIEW

**Comment by PrinceYoulou** [comment]
good job @steve111MV , create a branch so i can test it before merge

**Comment by steve111MV** [comment]
i'm already using a branch search_bar

**Comment by PrinceYoulou** [comment]
@steve111MV i want the result from the search bar to be just like what we have on the search page. the search function is working but it just populate the name of the drugstore, which is not relevant for the end user.

Check it!!!

**Comment by PrinceYoulou** [comment]
Replace the CSI and Labs database

**Pull request merged**
